name = "jera"
description = "A minimalistic colorful theme for Zola"
license = "MIT"
homepage = "https://codeberg.org/uncomfyhalomacro/zola"
# The minimum version of Zola required
min_version = "0.8.0"
# An optional live demo URL
demo = "https://uncomfyhalomacro.codeberg.page/jera/blog"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "socvirnyl estela"
homepage = "https://codeberg.org/uncomfyhalomacro/jera"
